server.port=9090
spring.application.name=stats-server

spring.datasource.url=${STATS_DB_URL:jdbc:postgresql://localhost:5432/statsdb}
spring.datasource.username=${STATS_DB_USER:postgres}
spring.datasource.password=${STATS_DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

logging.level.org.springframework.orm.jpa=INFO
logging.level.org.springframework.transaction=INFO